core/urls.py
from django.urls import path
from .views import index, criar_tarefa, alterar_status, ApagarTarefaView, criar_tarefa_pagina, tarefa_disponivel

#URLs da página
urlpatterns = [
    path('', index, name='index'),
    path('inicio', index, name='inicio'), 
    path('criar_tarefa_pagina', criar_tarefa_pagina, name='criar_tarefa_pagina'),
    path('tarefa_disponivel', tarefa_disponivel, name='tarefa_disponivel'),
    path('criar_tarefa/', criar_tarefa, name='criar_tarefa'),
    path('alterar_status/<int:tarefa_id>/', alterar_status, name='alterar_status'),  
    path('apagar_tarefa/<int:tarefa_id>/', ApagarTarefaView.as_view(), name='apagar_tarefa'),
]

unmep/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

admin.AdminSite.site_header = 'Página do Administrador'
admin.AdminSite.site_title = 'TarefaNest'
admin.AdminSite.index_title = 'Banco de Dados TarefaNest'

core/models.py
from django.db import models

# Método construtor onde possuí os atributos da Tarefa:
class Tarefa(models.Model):
    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('executando', 'Executando'),
        ('concluida', 'Concluída'),
    ]

    titulo = models.CharField(max_length=200)
    descricao = models.CharField(max_length=5000)
    data = models.DateField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente')

    def __str__(self):
        return self.titulo

core/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = ['titulo', 'descricao', 'data', 'status']

core/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.contrib import messages
from django.views import View
from .models import Tarefa

from .forms import TarefaForm
from .models import Tarefa

# Método que chama o index.html + outros dados como os atributos da classe tarefa
def index(request):
    tarefas = Tarefa.objects.all()

    context = {
        'tarefas': tarefas,
    }
    return render(request, 'index.html', context)

def criar_tarefa_pagina(request):
    tarefas = Tarefa.objects.all()

    context = {
        'tarefas': tarefas,
    }
    return render(request, 'criar_tarefa.html', context)

def tarefa_disponivel(request):
    tarefas = Tarefa.objects.all()

    context = {
        'tarefas': tarefas,
    }
    return render(request, 'tarefa_disponivel.html', context)


# Método feito para criar uma tarefa nova pela página HTML
def criar_tarefa(request):
    if request.method == 'POST':
        form = TarefaForm(request.POST)
        if form.is_valid():
            form.save()

            messages.success(request, 'Tarefa adicionada com sucesso!')

            return redirect('criar_tarefa_pagina')
    else:
        form = TarefaForm()

    return render(request, 'criar_tarefa.html', {'form': form})

# Método feito para alterar o status da tarefa pela página HTML
@require_POST
def alterar_status(request, tarefa_id):
    tarefa = get_object_or_404(Tarefa, id=tarefa_id)
    novo_status = request.POST.get('novo_status')

    if novo_status in ['pendente', 'executando', 'concluida']:
        tarefa.status = novo_status
        tarefa.save()

    return redirect('tarefa_disponivel')

class ApagarTarefaView(View):
    def post(self, request, tarefa_id):
        tarefa = get_object_or_404(Tarefa, id=tarefa_id)
        tarefa.delete()
        return redirect('tarefa_disponivel')

core/templates/criar_tarefa.html
{% load static %}
<!--  
Programa feito para a atividade de estágio da unMEP
Feito por Luiz Henrique Carneiro Carvalho
-->
<!DOCTYPE html>
<html lang="pt-br" class="min-vh-100">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <link rel="icon" href="/static/images/notas.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <title>TarefaNest - Sua Lista de Tarefas</title>
</head>

<body class="d-flex flex-column min-vh-100">
    <!-- Navbar da página -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container d-flex justify-content-between">
            <div class="d-flex">
                <a class="navbar-brand" href="inicio"><img id="nav-logo" class="logo_style"
                        src="{% static 'images/notas.png' %}" alt="TarefaNest Logo-Marca"></a>
                <a class="navbar-brand" href="inicio">TarefaNest</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="criar_tarefa_pagina">Criar Tarefa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="tarefa_disponivel">Tarefas Disponíveis</a>
                    </li>
                </ul>
                <div class="ms-auto">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="admin">Página do Administrador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- Conteiner para exibir "Mensagem enviada com sucesso!" -->
    <div class="container mt-3">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <!-- Card onde você adiciona uma tarefa nova -->
    <div class="container mt-5 mb-5 flex-grow-1">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="text-center mb-4">Criar Nova Tarefa</h2>
                        <form method="POST" action="{% url 'criar_tarefa' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="id_titulo">Título:</label>
                                <input type="text" name="titulo" class="form-control" id="titulo" required>
                            </div>

                            <div class="form-group mt-2">
                                <label for="id_descricao">Descrição:</label>
                                <textarea name="descricao" class="form-control" id="descricao" rows="4"
                                    required></textarea>
                            </div>

                            <div class="form-group mt-2">
                                <label for="id_data">Data:</label>
                                <input type="date" name="data" class="form-control" id="data" required>
                            </div>

                            <div class="form-group mt-2">
                                <label for="id_status">Status:</label>
                                <select name="status" class="form-control" id="status" required>
                                    <option value="pendente">Pendente</option>
                                    <option value="executando">Executando</option>
                                    <option value="concluida">Concluída</option>
                                </select>
                            </div>

                            <button type="submit" class="btn btn-primary mt-5">Criar Tarefa</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Footer da página -->
    <footer class="bg-dark text-white text-center py-3">
        <div class="container">
            <p class="text-center mt-2"> Programa feito por Luiz Henrique Carneiro Carvalho</p>
            <a class="btn text-white" data-mdb-ripple-init style="background-color: #0082ca;" target="_blank"
                href="https://www.linkedin.com/in/luizhenriqueccarvalho/" role="button">
                <i>LinkedIn</i>
            </a>
            <a class="btn text-white" data-mdb-ripple-init style="background-color: #333333;" target="_blank"
                href="https://github.com/Dom-Luiz-III" role="button">
                <i>GitHub</i>
            </a>
        </div>
    </footer>

    <!-- Links de script do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-U7bukf27M4plJc6CCr9P5mHOfY8gmebp2sAO9mKzDjDcQq3ksmaP6p6XN4lZhKg3"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

core/templates/index.html
{% load static %}
<!--  
Programa feito para a atividade de estágio da unMEP
Feito por Luiz Henrique Carneiro Carvalho
-->
<!DOCTYPE html>
<html lang="pt-br" class="min-vh-100">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  <link rel="icon" href="/static/images/notas.ico" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
  <title>TarefaNest - Sua Lista de Tarefas</title>
</head>

<body class="d-flex flex-column min-vh-100">
  <!-- Navbar da página -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary flex-grow-1">
    <div class="container d-flex justify-content-between">
      <div class="d-flex">
        <a class="navbar-brand" href=""><img id="nav-logo" class="logo_style" src="{% static 'images/notas.png' %}"
            alt="TarefaNest Logo-Marca"></a>
        <a class="navbar-brand" href="">TarefaNest</a>
      </div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="criar_tarefa_pagina">Criar Tarefa</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="tarefa_disponivel">Tarefas Disponíveis</a>
          </li>
        </ul>
        <div class="ms-auto">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="admin">Página do Administrador</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <!-- Card de introdução -->
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h1 class="text-center mb-4">Bem-vindo ao TarefaNest</h1>
        <p class="text-center">Sua solução simples para gerenciar suas tarefas diárias da unMEP.</p>
      </div>
    </div>
  </div>

  <!-- Card de descrição do site -->
  <div class="card-group container mb-5">
    <div class="card">
      <img src="{% static 'images/equipe.avif' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Organize a rotina da sua equipe!
        </h5>
        <p class="card-text">Gerencie suas tarefas de forma eficiente e alcance a produtividade desejada.</p>
      </div>
    </div>
    <div class="card">
      <img src="{% static 'images/pessoa_anotando.avif' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Comece agora mesmo!
        </h5>
        <p class="card-text">Registre suas tarefas e mantenha-se produtivo.</p>
      </div>
    </div>
    <div class="card mb-5">
      <img src="{% static 'images/bloco.jpg' %}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title text-center">Desperte Sua Eficiência!</h5>
        <p class="card-text">Otimize seu tempo e alcance seus objetivos através do registro e acompanhamento das suas
          atividades diárias.</p>
      </div>
    </div>
  </div>

  <!-- Botão que redireciona para Criar Tarefa -->
  <a class="btn btn-primary btn-lg d-grid gap-2 col-3 mx-auto" href="criar_tarefa_pagina" role="button"
    aria-disabled="true">Criar Tarefa</a>

  <!-- Footer da página -->
  <footer class="bg-dark text-white text-center py-3 mt-5">
    <div class="container">
      <p class="text-center mt-2"> Programa feito por Luiz Henrique Carneiro Carvalho</p>
      <a class="btn text-white" data-mdb-ripple-init style="background-color: #0082ca;" target="_blank"
        href="https://www.linkedin.com/in/luizhenriqueccarvalho/" role="button">
        <i>LinkedIn</i>
      </a>
      <a class="btn text-white" data-mdb-ripple-init style="background-color: #333333;" target="_blank"
        href="https://github.com/Dom-Luiz-III" role="button">
        <i>GitHub</i>
      </a>
    </div>
  </footer>

  <!-- Links de script do Bootstrap -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-U7bukf27M4plJc6CCr9P5mHOfY8gmebp2sAO9mKzDjDcQq3ksmaP6p6XN4lZhKg3"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>

core/templates/tarefa_disponivel.html
{% load static %}
<!--  
Programa feito para a atividade de estágio da unMEP
Feito por Luiz Henrique Carneiro Carvalho
-->
<!DOCTYPE html>
<html lang="pt-br" class="min-vh-100">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <link rel="icon" href="/static/images/notas.ico" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/index_style.css' %}">
    <title>TarefaNest - Sua Lista de Tarefas</title>
</head>

<body  class="d-flex flex-column min-vh-100">
    
    <!-- Navbar da página -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container d-flex justify-content-between">
            <div class="d-flex">
                <a class="navbar-brand" href="inicio"><img id="nav-logo" class="logo_style"
                        src="{% static 'images/notas.png' %}" alt="TarefaNest Logo-Marca"></a>
                <a class="navbar-brand" href="inicio">TarefaNest</a>
            </div>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="criar_tarefa_pagina">Criar Tarefa</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="tarefa_disponivel">Tarefas Disponíveis</a>
                    </li>
                </ul>
                <div class="ms-auto">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="admin">Página do Administrador</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

    <!-- Tabela para ver todas as tabelas armazenadas no banco de dados, também é possível mudar o status ou apagar por aqui -->
    <div class="container bg-body mt-5 flex-grow-1">
        <h1 class="text-center mb-4">Tarefas Disponíveis</h1>
        <div class="container mx-auto text-center table-responsive">
            <table class="table table-striped table-bordered mx-auto text-center">
                <thead>
                    <tr>
                        <th>Título</th>
                        <th>Descrição</th>
                        <th>Data</th>
                        <th style="width: 130px;">Status</th>
                        <th>Ação</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tarefa in tarefas %}
                    <tr>
                        <td>{{ tarefa.titulo }}</td>
                        <td>{{ tarefa.descricao }}</td>
                        <td>{{ tarefa.data }}</td>
                        <td class="col-sm-3 col-md-2 col-lg-2">
                            <form method="POST" action="{% url 'alterar_status' tarefa.id %}">
                                {% csrf_token %}
                                <select name="novo_status" style="width: 130px;" class="form-control btn btn-secondary text-center"
                                    onchange="this.form.submit()">
                                    <option value="pendente" {% if tarefa.status == 'pendente' %}selected{% endif %}>Pendente</option>
                                    <option value="executando" {% if tarefa.status == 'executando' %}selected{% endif %}>Executando</option>
                                    <option value="concluida" {% if tarefa.status == 'concluida' %}selected{% endif %}>Concluída</option>
                                </select>
                            </form>
                        </td>
                        <td>
                            <form method="POST" action="{% url 'apagar_tarefa' tarefa.id %}"
                                onsubmit="return confirm('Tem certeza que deseja apagar essa tarefa?');">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Apagar</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <!-- Footer da página -->
    <footer class="bg-dark text-white text-center py-3 mt-5">
        <div class="container">
            <p class="text-center mt-2"> Programa feito por Luiz Henrique Carneiro Carvalho</p>
            <a class="btn text-white" data-mdb-ripple-init style="background-color: #0082ca;" target="_blank"
                href="https://www.linkedin.com/in/luizhenriqueccarvalho/" role="button">
                <i>LinkedIn</i>
            </a>
            <a class="btn text-white" data-mdb-ripple-init style="background-color: #333333;" target="_blank"
                href="https://github.com/Dom-Luiz-III" role="button">
                <i>GitHub</i>
            </a>
        </div>
    </footer>
    
    <!-- Links de script do Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-U7bukf27M4plJc6CCr9P5mHOfY8gmebp2sAO9mKzDjDcQq3ksmaP6p6XN4lZhKg3"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>